# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9d875e2ecc70e7dfec46fe64aca0a17f244babc61eb08d489ae64b5db4150d2e404353d874ffd78f219e4da989b8442e268e7422e6388ce1b85f96c020d243

test:
  secret_key_base: f68ef52227bd27c7832477950391bf3db1296bedbf0d9e4d1630427386584ddcffb8722702be2a55b4071401dd21508aeec55d74b93702caf40d261cb6f73d25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
